# Generated by Django 5.2.1 on 2025-07-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_couponusage_order'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['used_at'], name='coupons_cou_used_at_2fc071_idx'),
        ),
    ]
