# Generated by Django 5.2.1 on 2025-07-25 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_couponusage_coupons_cou_used_at_2fc071_idx'),
        ('orders', '0004_alter_wallet_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='couponnotification',
            name='coupon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='coupons.coupon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponnotification',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_notifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponusage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponvalidationhistory',
            name='coupon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='validation_history', to='coupons.coupon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponvalidationhistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_validation_history', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referralcoupon',
            name='base_coupon',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='referral_details', to='coupons.coupon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referralcoupon',
            name='referrer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_referrals', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together={('coupon', 'order')},
        ),
        migrations.AddIndex(
            model_name='couponnotification',
            index=models.Index(fields=['user', 'read_at'], name='coupons_cou_user_id_aae124_idx'),
        ),
        migrations.AddIndex(
            model_name='couponnotification',
            index=models.Index(fields=['notification_type'], name='coupons_cou_notific_be3f48_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'user'], name='coupons_cou_coupon__830da4_idx'),
        ),
        migrations.AddIndex(
            model_name='couponvalidationhistory',
            index=models.Index(fields=['coupon', 'user'], name='coupons_cou_coupon__2d0279_idx'),
        ),
        migrations.AddIndex(
            model_name='couponvalidationhistory',
            index=models.Index(fields=['attempted_at'], name='coupons_cou_attempt_690bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcoupon',
            index=models.Index(fields=['referrer'], name='coupons_ref_referre_78e6bd_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcoupon',
            index=models.Index(fields=['base_coupon'], name='coupons_ref_base_co_ff2a3d_idx'),
        ),
    ]
