# Generated by Django 5.2.1 on 2025-05-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_customerprofile'),
    ]

    operations = [
    ]
