# Generated by Django 5.2.1 on 2025-07-17 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_remove_product_image_product_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('high_demand', 'High Demand'), ('price_change', 'Price Change')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('message', models.TextField()),
                ('threshold_value', models.IntegerField(help_text='Threshold that triggered the alert (e.g., stock level)')),
                ('current_value', models.IntegerField(help_text='Current value when alert was created')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='products.product')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notification_method', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App Notification'), ('sms', 'SMS')], max_length=20)),
                ('is_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_notifications', to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.productalert')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productalert',
            index=models.Index(fields=['product', 'alert_type', 'is_active'], name='alerts_prod_product_d252d0_idx'),
        ),
        migrations.AddIndex(
            model_name='productalert',
            index=models.Index(fields=['created_at'], name='alerts_prod_created_bfd6c4_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['user', 'read_at'], name='alerts_aler_user_id_8f5b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['sent_at'], name='alerts_aler_sent_at_bd8e96_idx'),
        ),
    ]
